name: RASCL_Influenza
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - biopython=1.81
  - hyphy=2.5.47
  - raxml-ng=1.1.0 
  - snakemake=7.22.0
  - tn93=1.0.9
  - python-bioext=0.20.4
  - python=3.9
